version: 2.1

executors:
  docker-executor:
    docker:
      - image: circleci/python:3.10

jobs:
  build-and-push:
    executor: docker-executor
    steps:
      # Step 1: Checkout the code
      - checkout

      - run:
          name: Authenticate with Docker Hub
          command: |
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin

      # Step 3: Build the Docker image
      - run:
          name: Build Docker Image
          command: |
            docker build -t $DOCKERHUB_USERNAME/subtraction-service:latest .
            docker tag $DOCKERHUB_USERNAME/subtraction-service:latest $DOCKERHUB_USERNAME/subtraction-service:$(echo $CIRCLE_SHA1 | cut -c -7)

      # Step 4: Push the Docker image to Docker Hub
      - run:
          name: Push Docker Image to Docker Hub
          command: |
            docker push $DOCKERHUB_USERNAME/subtraction-service:latest
            docker push $DOCKERHUB_USERNAME/subtraction-service:$(echo $CIRCLE_SHA1 | cut -c -7)

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build-and-push:
          context:
            - dockerhub
          filters:
            branches:
              only: main

